.TH LIBOPENSHOT-AUDIO 1 "August 8, 2012" Linux "User Manuals"
.SH NAME
openshot-audio-demo \- Display system info and play test sound

.SH SYNOPSIS
.B openshot-audio-demo

.SH DESCRIPTION
Display information about detected audio interfaces, then play a test sound.
Uses the libopenshot-audio library.

.TP
.B More information
 Project Website: http://www.openshot.org/

.SH AUTHOR
libopenshot was written by Jonathan Thomas <jonathan@openshot.org>.

.PP
This manual page was written by Jonathan Thomas <jonathan@openshot.org>,
for the Debian project (and may be used by others).
