.TH LIBOPENSHOT SECTION "August  8, 2012"
.SH NAME
openshot-audio-test-sound \- Play test sound

.SH SYNOPSIS
.B openshot-audio-test-sound 

.SH DESCRIPTION
Play a test sound using the libopenshot-audio library.

.TP
.B More information
 Project Website: http://www.openshot.org/

.SH AUTHOR
libopenshot was written by <upstream author>.

.PP
This manual page was written by Jonathan <jonathan@unknown>,
for the Debian project (and may be used by others).
